// LOCALHOST
### Get all products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/6691e9b00c5bee956a757ef5

### Create product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
    "productName": "Ergonomic Cotton Keyboara",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "price": 99.99,
    "category": "electronics",
    "stockQuantity": 200
}

### Update product
PUT http://localhost:3000/products/669289f0c1bcc73fe568190 HTTP/1.1
content-type: application/json

{
    "productName": "Ergonomic Cotton Keyboard",
    "descriptio": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "price": 99.99,
    "category": "electronics",
    "stockQuantity": 200,
}

### Delete product
DELETE http://localhost:3000/products/669329eaf8541ec5c7c5f7c HTTP/1.1


// PRODUCTION
### Get all products
GET https://cse341-project2-hhgl.onrender.com/products

### Get product by id
GET https://cse341-project2-hhgl.onrender.com/products/669203474f9fad205da9e298

### Create product
POST https://cse341-project2-hhgl.onrender.com/products HTTP/1.1
content-type: application/json

{
    "productName": "Ergonomic Cotton Keyboaraaaaad",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "price": 99.99,
    "category": "electronics",
    "stockQuantity": 200
}

### Update product
PUT https://cse341-project2-hhgl.onrender.com/products/666f6eb0845c73c900052e7f HTTP/1.1
content-type: application/json

{
    "productName": "Ergonomic Cotton Keyboardas",
    "description": "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
    "price": "199.99",
    "category": "electronics",
    "stockQuantity": 200
}

### Delete product
DELETE https://cse341-project2-hhgl.onrender.com/products/669203474f9fad205da9e298 HTTP/1.1